title = "gitleaks config"

[allowlist]
description = "global allow list"
paths = [
    # Ignore the key.pem in the root of the repo.
    '''key\.pem$''',
    # Ingore the log files containing example output.
    '''log\/[^\/]+.log$''',
    # Ingore the log files containing example output in the old commits.
    '''[^\/]+.log$''',
    # Ignore the c file containing the false positive comment for the private
    # key.
    '''20657\.c$''',
]
